Do not require QEMU extra options
Without this fix ./run_glibc_testsuite.py without
--qemu-extra-opts will fail with:
Traceback (most recent call last):
  File "./run_glibc_testsuite.py", line 225, in <module>
    sys.exit(main())
  File "./run_glibc_testsuite.py", line 193, in main
    args.qemu_extra_opts.split(' '),
AttributeError: 'NoneType' object has no attribute 'split'

Signed-off-by: Vladimir Isaev <isaev@synopsys.com>